apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build-push

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      artifact-id:
        value: ${{ jobs.build.outputs.artifact-id }}
      version:
        value: ${{ jobs.build.outputs.version }}
      image:
        value: ${{ jobs.build.outputs.image }}

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: read

jobs:
  test:
    uses: ./.cloudbees/workflows/test.yaml
    vars: inherit
    secrets: inherit

  build:
    needs: test
    uses: ./.cloudbees/workflows/build.yaml
    vars: inherit
    secrets: inherit
