apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: test-oidc

on:
  workflow_dispatch:

permissions:
  scm-token-own: read
  scm-token-org: read

jobs:
  build:
    permissions:
      id-token: write
      scm-token-own: read
      scm-token-org: read

    steps:
      - name: Login to AWS via OIDC
        uses: cloudbees-io/configure-aws-credentials@v1
        id: aws-login
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: "3600" # optional

      - name: Run AWS CLI commands
        uses: docker://public.ecr.aws/aws-cli/aws-cli
        shell: sh
        run: |
          aws sts get-caller-identity
          aws configure list